src/mysite/mysite/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.views import login

from rest_framework.urlpatterns import format_suffix_patterns
from resources.views import EstudianteList
from resources.views import EvaluacionList
from resources.views import RegistrarView
from django.contrib.auth.decorators import login_required
from django.contrib.auth import views as auth_views




urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('resources.urls', namespace='resources')),
    url(r'^$', login, {'template_name': 'resources/login_form.html'}, name='user_login'),
    url(r'^accounts/user_login/$', login, {'template_name': 'resources/login_form.html'}, name='user_login'),
    url(r'^registrate/$', RegistrarView.as_view(), name='registrar'),
    #url(r'^registrar', RegistroUsuario.as_view(), name='registrar'),

    #Password Reset URL's
    url(r'^password_reset/$', auth_views.password_reset, name='password_reset'),
    url(r'^password_reset/done/$', auth_views.password_reset_done, name='password_reset_done'),
    url(r'^password_reset/confirm/(?P<uidb64>[\w-]+)/(?P<token>[\w-]+)/$', auth_views.password_reset_confirm,
        name='password_reset_confirm'),
    url(r'^password_reset/complete/$', auth_views.password_reset_complete, name='password_reset_complete'),

    #url(r'^', include('django.contrib.auth.urls')),


    #estudiantes y evaluaciones son listas de Rest (Servicio RESTful)
    url(r'^estudiantes/', login_required(EstudianteList.as_view()), name='estudiantes'),
    url(r'^evaluaciones/', login_required(EvaluacionList.as_view()), name='evaluaciones'),
]

urlpatterns = format_suffix_patterns(urlpatterns)


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/mysite/resources/urls.py
# resources/urls.py
from django.conf.urls import url
from . import views
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import logout_then_login

app_name = 'resources'

urlpatterns = [
    # /
    url(r'^index/$', login_required(views.IndexView.as_view()), name='index'),
    url(r'^reportes/$', login_required(views.ReportesView.as_view()), name='reportes'),

    #lectura/estudiante/
    #url(r'lectura/estudiante/$', login_required(views.LecturaEstudianteView.as_view()), name='estudiante-lectura'),

    # profesor/perfil/<profesor_id>
    url(r'^profesor/perfil/$', login_required(views.ListProfesorLogeado.as_view()), name='profesor-perfil'),
    #url(r'^profesor/perfil/(?P<pk>[0-9]+)/$', login_required(views.ListProfesorLogeado.as_view()), name='profesor-perfil'),

    # estudiante/<estudiante_id>  --> En la URL se encuentra como: estudiante/1 , donde el 1 seria el ID del estudiante.
    url(r'^estudiante/(?P<pk>[0-9]+)/$', login_required(views.DetailView.as_view()), name='detalles'),
    # Por razones de prueba estoy validando solo ID numericos.

    url(r'estudiante/buscar/$', login_required(views.busqueda), name='estudiante-buscar'),

    url(r'listado/estudiantes/$', login_required(views.ListEstudiantes.as_view()), name='listado-estudiantes'),

    # /resources/estudiante/add/
    url(r'estudiante/add/$', login_required(views.CrearEstudiante.as_view()), name='estudiante-add'),

    # /resources/lectura/add/
    url(r'lectura/add/$', login_required(views.CrearLectura.as_view()), name='lectura-add'),

    # /resources/listado/lecturas/
    url(r'listado/lecturas/$', login_required(views.ListLecturas.as_view()), name='listado-lecturas'),

    # /resources/lectura/update/2/
    url(r'lectura/update/(?P<pk>[0-9]+)/$', login_required(views.UpdateLectura.as_view()), name='lectura-update'),

    # /resources/lectura/2/delete
    url(r'lectura/(?P<pk>[0-9]+)/delete/$', login_required(views.DeleteLectura.as_view()), name='lectura-delete'),

    # /resources/estudiante/update/2/
    url(r'estudiante/update/(?P<pk>[0-9]+)/$', login_required(views.UpdateEstudiante.as_view()), name='estudiante-update'),

    # /resources/estudiante/2/delete
    url(r'estudiante/(?P<pk>[0-9]+)/delete/$', login_required(views.DeleteEstudiante.as_view()), name='estudiante-delete'),

    # evaluacion/<evaluacion_id>
    url(r'^evaluacion/(?P<pk>[0-9]+)/$', login_required(views.DetailViewEvaluacion.as_view()), name='detalles-evaluacion'),

    # /evaluacion/
    url(r'evaluacion/add/$', login_required(views.RealizarEvaluacionVista.as_view()), name='realizar-evaluacion'),

    # /resources/estudiante/2/delete
    url(r'evaluacion/delete/(?P<eva_id>[\d]+)/$', login_required(views.DeleteEvaluacion), name='evaluacion-delete'),

    # api/chart/data/ --> Ruta para generar la grafica.
    url(r'appleo/api/chart/data/', login_required(views.chart)),

    url(r'logout/', logout_then_login, name='logout'),



]

src/mysite/resources/models.py
from django.db import models
from django.core.urlresolvers import reverse
from django.contrib.auth.models import User
from phone_field import PhoneField
from datetime import datetime

#from django.dispatch import receiver
#from django.db.models.signals import post_save
#from phonenumber_field.modelfields import PhoneNumberField

# Crea tus Modelos aqui.



class Profesor(models.Model):
    usuario = models.OneToOneField(User, on_delete=models.CASCADE)
    direccion = models.CharField(max_length=250, blank=True)
    telefono = PhoneField(blank=True, help_text='Teléfono de contacto')

    #def from_db_value(self, usuario, direccion, telefono):

    # def __init__(self, usuario, direccion, telefono):
    #     # Input parameters are lists of cards ('Ah', '9s', etc.)
    #     self.usarioario = usuario
    #     self.direccion = direccion
    #     self.telefono = telefono

    def get_absolute_url(self):
        return reverse('resources:profesor-perfil', kwargs={'pk': self.pk})

    def __str__(self):
        return self.usuario.username

# @receiver(post_save, sender=User)
# def crear_usuario_profesor(sender, instance, created, **kwargs):
#     if created:
#         Profesor.objects.create(usuario=instance)
#
#
# @receiver(post_save, sender=User)
# def guardar_usuario_profesor(sender, instance, **kwargs):
#     instance.profesor.save()

#Modelo de los Grupos:
#class Grupo(models.Model):


class Estudiante(models.Model):
    #profesor =models.OneToOneField(Profesor, on_delete=models.CASCADE)  #Es mejor usar OneToOneField y eliminar el (unique = True).
    #profesor = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    nombres = models.CharField(max_length=250)
    apellidos = models.CharField(max_length=250)
    genero = models.CharField(max_length=10)
    edad = models.CharField(max_length=8)
    foto = models.FileField()
    #es_favorito = models.BooleanField(default=False)
    #user = models.OneToOneField(User, on_delete=models.CASCADE)

    def get_absolute_url(self):
        return reverse('resources:detalles', kwargs={'pk': self.pk})

    def __str__(self):
        return self.nombres + ' - ' + self.apellidos

class Lectura(models.Model):
    titulo = models.CharField(max_length=250)
    texto = models.CharField(max_length=1500)


#Realizar Evaluaciones:
class Evaluacion(models.Model):
    estudiante = models.ForeignKey(Estudiante, on_delete=models.CASCADE)
    texto_a_leer = models.CharField(max_length=500, default='María conoce un niño con muy mal carácter en su escuela llamado Juan Carlos')
    evaluacion_tipo = models.CharField(max_length=15)  # Los tipos de evaluacion son de Comprension o Fluidez Lectora.
    fluidez_lectora = models.CharField(max_length=25, default='')
    tipo_lectura = models.CharField(max_length=250, default='')  # Tipos: LENTA, MUY LENTA, RAPIDA, etc.S
    es_favorito = models.BooleanField(default=False)
    comentario = models.CharField(max_length=100, blank=True)
    fecha = models.DateTimeField(default=datetime.now, blank=False)
    lectura = models.ForeignKey(Lectura, on_delete=models.CASCADE, blank=True, default='')

    #Los datos a imprimir en la graficas:
    def __unicode__(self):
        return u'%s %s %s' % (self.fluidez_lectora, self.tipo_lectura, self.fecha)

    def get_absolute_url(self):
        return reverse('resources:detalles-evaluacion', kwargs={'pk': self.pk})

    def __str__(self):
        return self.fluidez_lectora + ' - ' + self.tipo_lectura + ' - ' + self.fecha





#Las preguntas se usan para implementar Cloze.

class Pregunta(models.Model):
    lectura = models.ForeignKey(Lectura, on_delete=models.CASCADE, blank=True, default='')
    nombre_p1 = models.CharField(max_length=150, blank=True)
    enunciado_p1 = models.CharField(max_length=512, blank=True)
    nombre_p2 = models.CharField(max_length=150, blank=True)
    enunciado_p2 = models.CharField(max_length=512, blank=True)
    nombre_p3 = models.CharField(max_length=150, blank=True)
    enunciado_p3 = models.CharField(max_length=512, blank=True)
    nombre_p4 = models.CharField(max_length=150, blank=True)
    enunciado_p4 = models.CharField(max_length=512, blank=True)
    nombre_p5 = models.CharField(max_length=150, blank=True)
    enunciado_p5 = models.CharField(max_length=512, blank=True)



class Fluidez(models.Model):
    evaluacion = models.ForeignKey(Evaluacion, on_delete=models.CASCADE)
    ppm = models.CharField(max_length=8)
    tipo_lectura = models.CharField(max_length=250)


class Comprension(models.Model):
    evaluacion = models.ForeignKey(Evaluacion, on_delete=models.CASCADE)
    comprension_porcentaje = models.CharField(max_length=4)


#Realizar Evaluaciones:
#class EvaluacionForm(models.Model):
    #texto_a_leer = models.CharField(max_length=500, default='María conoce un niño con muy mal carácter en su escuela')


    #resultado = JSONField(max_length=200, default='')
    #Este ultimo campo es la respuesta luego de evaluar la lectura --> campo imprime resultado en un json.

    #resultado = models.JSONField(max_length=200)

src/mysite/resources/templates/resources/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}AppLeo{% endblock %}</title>
    <!-- Carga la ruta a tus archivos estáticos -->
    {% load staticfiles %}
    <!--<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">-->
    <!--<link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>-->
    <!--<link rel="stylesheet" type="text/css" href="{% static 'resources/style.css' %}"/>-->
    <!--&lt;!&ndash;General CSS&ndash;&gt;-->
    <!--<link rel="stylesheet" type="text/css" href="{% static 'resources/js/modules/bootstrap/css/bootstrap.min.css' %}"/>-->
    <!--<link rel="stylesheet" type="text/css" href="{% static 'resources/js/modules/fontawesome/css/all.min.css' %}"/>-->
    <!--&lt;!&ndash;CSS&ndash;&gt;-->
    <!--<link rel="stylesheet" type="text/css" href="{% static 'resources/js/modules/jqvmap/dist/jqvmap.min.css' %}"/>-->
    <!--<link rel="stylesheet" type="text/css" href="{% static 'resources/js/modules/summernote/summernote-bs4.css' %}"/>-->
    <!--<link rel="stylesheet" type="text/css"-->
          <!--href="{% static 'resources/js/modules/owlcarousel2/dist/assets/owl.carousel.min.css' %}"/>-->
    <!--<link rel="stylesheet" type="text/css"-->
          <!--href="{% static 'resources/js/modules/owlcarousel2/dist/assets/owl.theme.default.min.css' %}"/>-->
    <!--&lt;!&ndash;Template CSS&ndash;&gt;-->
    <!--<link rel="stylesheet" type="text/css" href="{% static 'resources/css/style.css' %}"/>-->
    <!--<link rel="stylesheet" type="text/css" href="{% static 'resources/css/components.css' %}"/>-->



    <!--<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>-->
    <!--<script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>-->
    <script src="{% static 'resources/js/modules/jquery.min.js' %}"></script>
    <script src="{% static 'resources/js/echarts.min.js' %}"></script>
    <script src="{% static 'resources/js/moment.min.js' %}"></script>

    <script src="{% static 'resources/js/main.js' %}"></script>


    <!-- Jean Front-End-->

    <link rel="stylesheet" href="{% static 'resources/assets/bootstrap/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i">
    <link rel="stylesheet" href="{% static 'resources/assets/fonts/fontawesome-all.min.css' %}">

</head>
<!--<body>-->

<!--<nav class="navbar navbar-expand-lg main-navbar">-->
    <!--<ul class="navbar-nav mr-3">-->
        <!--<li><a href="#" data-toggle="sidebar" class="nav-link nav-link-lg" style=""><i class="fas fa-bars"></i></a>-->
        <!--</li>-->
        <!--<li><a href="#" data-toggle="search" class="nav-link nav-link-lg d-sm-none"><i-->
                <!--class="fas fa-search"></i></a></li>-->
    <!--</ul>-->

<!--</nav>-->


<body id="page-top">
<!--Side bar-->
<div id="wrapper">
    <nav class="navbar navbar-dark align-items-start sidebar sidebar-dark accordion bg-gradient-primary p-0">
        <div class="container-fluid d-flex flex-column p-3">
            <a class="navbar-brand d-flex justify-content-center align-items-center sidebar-brand m-0" href="#">
                <div class="sidebar-brand-text mx-3"><a href="{% url 'resources:index' %}">App Leo</a></div>
            </a>

            <!--<hr class="sidebar-divider my-0">-->
            <ul class="nav navbar-nav text-light" id="accordionSidebar">
                <li class="nav-item" role="presentation"><a class="nav-link" href="{% url 'resources:index' %}"><i class="fas fa-home"></i> <span>Inicio</span></a></li>

                <li class="menu-header">Evaluaciones</li>
                <li class="{% if "/evaluacion/add" in request.path %}active{% endif %}">
                <a class="nav-link" href="{% url 'resources:realizar-evaluacion' %}">
                <i class="fas fa-file-signature "></i> <span>Realizar evaluación</span></a></li>

                <li class="menu-header">Lecturas</li>
                <li class="{% if "lectura/add" in request.path %}active{% endif %}">
                <a class="nav-link" href="{% url 'resources:lectura-add' %}">
                <i class="fas fa-file-archive "></i> <span>Cargar Lectura</span></a></li>

                <li class="{% if "/listado/lecturas" in request.path %}active{% endif %}">
                <a class="nav-link" href="{% url 'resources:listado-lecturas' %}">
                    <i class="fas fa-file "></i> <span>Listado Lecturas</span></a>
                </li>

                <li class="menu-header">Reportes</li>
                <li class="{% if "/reportes" in request.path %}active{% endif %}">
                <a class="nav-link" href="{% url 'resources:reportes' %}">
                    <i class="fas fa-file-signature "></i> <span>Reportes</span></a>
                </li>

                <li class="{% if "/listado/estudiantes" in request.path %}active{% endif %}">
                <a class="nav-link" href="{% url 'resources:listado-estudiantes' %}">
                    <i class="fas fa-users "></i> <span>Listado estudiantes</span></a>
                </li>

            </ul>
            <div class="text-center d-none d-md-inline"><button class="btn rounded-circle border-0" id="sidebarToggle" type="button"></button></div>
        </div>

        <!--Nav bar-->
    </nav>
    <div class="d-flex flex-column" id="content-wrapper">
        <div id="content">
            <nav class="navbar navbar-light navbar-expand bg-white shadow mb-4 topbar static-top">
                <div class="container-fluid"><button class="btn btn-link d-md-none rounded-circle mr-3" id="sidebarToggleTop" type="button"><i class="fas fa-bars"></i></button>
                    <form class="form-inline d-none d-sm-inline-block mr-auto ml-md-3 my-2 my-md-0 mw-100 navbar-search" role="search" method="get" action="{% url 'resources:estudiante-buscar' %}">
                        <div class="input-group">
                            <input type="text" class="bg-light form-control border-0 small" id="q" aria-controls="dataTable" placeholder="Buscar" name="nombres" required>
                            <div class="input-group-append"><button class="btn btn-primary py-0" type="submit"><i class="fas fa-search"></i></button></div>

                        </div>

                        <script>
                            $(document).ready(function(){

                                $("#q").on('change', function () {

                                    buscar();
                                })

                            });


                            function buscar() {

                                $.ajax({
                                    type: 'POST',
                                    data: $('#form').serialize(),
                                    url: "/estudiante/busqueda",
                                    success: function (res) {

                                        console.log(res);

                                    }

                                });


                            }
                        </script>
                    </form>
                    <ul class="nav navbar-nav flex-nowrap ml-auto">
                        <li class="nav-item dropdown d-sm-none no-arrow"><a class="dropdown-toggle nav-link" data-toggle="dropdown" aria-expanded="false" href="#"><i class="fas fa-search"></i></a>
                            <div class="dropdown-menu dropdown-menu-right p-3 animated--grow-in" role="menu" aria-labelledby="searchDropdown">
                                <form class="form-inline mr-auto navbar-search w-100">
                                    <div class="input-group"><input class="bg-light form-control border-0 small" type="text" placeholder="Search for ...">
                                        <div class="input-group-append"><button class="btn btn-primary py-0" type="button"><i class="fas fa-search"></i></button></div>
                                    </div>
                                </form>
                            </div>
                        </li>

                        </li>


                        <div class="d-none d-sm-block topbar-divider"></div>
                        <li class="nav-item dropdown no-arrow" role="presentation">
                            {% if user.is_authenticated %}
                                <div class="nav-item dropdown no-arrow"><a class="dropdown-toggle nav-link" data-toggle="dropdown" aria-expanded="false" href="#"><span class="d-none d-lg-inline mr-2 text-gray-600 small">Hola, {{ user.first_name }}</span><img class="border rounded-circle img-profile" src="{% static 'resources/assets/img/avatars/profe2.png' %}"></a></div>
                            {% else %}
                                <div class="nav-item dropdown no-arrow"><a class="dropdown-toggle nav-link" data-toggle="dropdown" aria-expanded="false" href="#"><span class="d-none d-lg-inline mr-2 text-gray-600 small">Regístrese o inicie sesión si desea</span><img class="border rounded-circle img-profile" src="{% static 'resources/assets/img/avatars/profe2.png' %}"></a></div>
                             {% endif %}
                                <div class="dropdown-menu shadow dropdown-menu-right animated--grow-in" role="menu">
                                        <div class="dropdown-divider"></div><a class="dropdown-item" role="presentation" href="{% url 'resources:logout' %}"><i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>&nbsp;Cerrar sesi&oacute;n</a></div>
                        </li>


                    </ul>
                </div>
            </nav>
            {% block body %}
            {% endblock %}

            <!--<div class="container-fluid">-->
                <!--<div class="card shadow">-->
                    <!--<div class="card-header py-3">-->
                        <!--<p class="text-primary m-0 font-weight-bold">Inicio</p>-->
                    <!--</div>-->

                    <!--<div class="card-body">-->

                    <!--</div>-->


                <!--</div>-->
            <!--</div>-->
        </div>


    </div><a class="border rounded d-inline scroll-to-top" href="#page-top"><i class="fas fa-angle-up"></i></a></div>


<footer class="bg-white sticky-footer">
    <div class="container my-auto">
        <div class="text-center my-auto copyright"><span>Copyright © APP LEO 2020</span></div>
    </div>
</footer>



<!-- jean Frontend -->
<script src="{% static 'resources/assets/js/jquery.min.js' %}"></script>
<script src="{% static 'resources/assets/bootstrap/js/bootstrap.min.js' %}"></script>
<script src="{% static 'resources/assets/js/chart.min.js' %}"></script>
<script src="{% static 'resources/assets/js/bs-init.js' %}"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.4.1/jquery.easing.js"></script>
<script src="{% static 'resources/assets/js/theme.js' %}"></script>


<script src="{% static 'resources/js/modules/popper.js' %}"></script>
<script src="{% static 'resources/js/modules/tooltip.js' %}"></script>
<script src="{% static 'resources/js/modules/bootstrap/js/bootstrap.min.js' %}"></script>
<script src="{% static 'resources/js/modules/nicescroll/jquery.nicescroll.min.js' %}"></script>
<script src="{% static 'resources/js/modules/moment.min.js' %}"></script>
<script src="{% static 'resources/js/stisla.js' %}"></script>
<script src="{% static 'resources/js/modules/summernote/summernote-bs4.js' %}"></script>
<script src="{% static 'resources/js/modules/chocolat/dist/js/jquery.chocolat.min.js' %}"></script>
<script src="{% static 'resources/js/page/index.js' %}"></script>
<script src="{% static 'resources/js/scripts.js' %}"></script>
<script src="{% static 'resources/js/custom.js' %}"></script>



</body>

</html>

src/mysite/resources/templates/resources/detalles.html
<div id="app">
    <div class="main-wrapper main-wrapper-1">
        <div class="navbar-bg"></div>
        {% extends 'resources/base.html' %}
        {% block title %}Detalles del Estudiante{% endblock %}
        {% block estudiantes_active %}active{% endblock %}

        {% block body %}
        <div class="main-content">
            <section class="section">
                <div class="section-header">
                    <h1>Detalles del estudiante</h1>

                </div>
                <div class="container-fluid songs-container">

                    <div class="row">

                        <!-- Izquierda Estudiante Info -->
                        <div class="col-sm-4 col-md-3">

                            <div class="card-wrap">
                                <div class="card-header">
                                    <a href="{% url 'resources:detalles' estudiante.id %}">
                                        {% if estudiante.foto %}
                                        <img src="{{ estudiante.foto.url }}" class="img-responsive" style="width: 150px;">
                                        {% else %}
                                        <h3>No hay imagen para mostrar</h3>
                                        {% endif %}
                                    </a>
                                </div>
                                <div class="card-body">
                                    <h4>{{ estudiante.nombres }} {{ estudiante.apellidos }}</h4>
                                    <small>
                                        <label>ID:{{ estudiante.id }} </label>
                                    </small>
                                </div>
                                &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<a href="{% url 'resources:estudiante-update' estudiante.id %}" class="btn btn-primary btn-sm"
                                   role="button">Editar</a>
                            </div>

                        </div>

                        <!-- Derecha Evaluacion Info -->
                        <div class="col-sm-8 col-md-9">

                            <ul class="nav nav-pills" style="margin-bottom: 10px;">
                                <li role="presentation" class="active"><a
                                        href="{% url 'resources:detalles' estudiante.id %}">Ver todo</a></li>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                                <li role="presentation"><a href="{% url 'resources:realizar-evaluacion' estudiante.id %}">Agregar Evaluación</a></li>
                            </ul>
                            <!--&nbsp;-->

                            <div class="panel panel-default">
                                <div class="panel-body">

                                    <h3>Todas las Evaluaciones</h3>

                                    {% if error_message %}
                                    <p><strong>{{ error_message }}</strong></p>
                                    {% endif %}

                                    <table class="table">
                                        <thead>
                                        <tr>
                                            <th>ID Evaluación</th>
                                            <th>Favorito</th>
                                            <th>Ver</th>
                                            <th>Acción</th>
                                        </tr>
                                        </thead>
                                        <tbody>
                                        {% for evaluacion in estudiante.evaluacion_set.all %}
                                        <tr>
                                            <td>{{ evaluacion.id }}</td>
                                            <td>
                                                <a href="#" class="btn-favorite"><span
                                                        class="glyphicon glyphicon-star {% if evaluacion.es_favorito %}active{% endif %}"></span></a>
                                            </td>
                                            <!-- Ver Detalles de la Evaluacion -->
                                            <td>
                                            <a href="{% url 'resources:detalles-evaluacion' evaluacion.id %}" class="btn btn-primary btn-sm"
                                               role="button">Ver Detalles</a>
                                            </td>
                                            <td>
                                                <!-- Eliminar Evaluacion -->
                                                <form action="{% url 'resources:evaluacion-delete' evaluacion.id%}" method="post" style="display: inline;" onclick="return confirm('¿Seguro que desea eliminar la Evaluación?');">
                                                    {% csrf_token %}
                                                    <input type="hidden" name="evaluacion_id" value="{{ evaluacion.id }}"/>
                                                    <button type="submit" class="btn btn-danger btn-xs">
                                                        <span class="glyphicon glyphicon-remove"></span>&nbsp; Eliminar
                                                    </button>
                                                </form>
                                            </td>

                                        </tr>
                                        {% endfor %}
                                        </tbody>
                                    </table>

                                </div>
                            </div>

                        </div>

                    </div>

                </div>
            </section>

        </div>
        {% endblock %}

    </div>
</div>

src/mysite/resources/templates/resources/estudiante_form.html
<div id="app">
    <div class="main-wrapper main-wrapper-1">
        <div class="navbar-bg"></div>
        {% extends 'resources/base.html' %}
        {% block title %}Agregar un Estudiante{% endblock %}
        {% block estudiantes_active %}active{% endblock %}


        {% block body %}
        <div style="padding-left: 5cm" class="main-content">
            <section class="section">
                <div class="section-header">
                    <h1>Datos del estudiante</h1>

                </div>
                <div class="main-content container-fluid">
                    <div class="row">

                        <div class="col-sm-12 col-md-7">
                            <div class="panel panel-default">
                                <div class="panel-body">

                                    <form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
                                        {% csrf_token %}
                                        {% include 'resources/form-template.html' %}
                                        <div class="form-group">
                                            <div class="col-sm-offset-5 col-sm-15">
                                                <button type="submit" class="btn btn-success">Enviar</button>
                                            </div>
                                        </div>
                                    </form>

                                </div>

                            </div>
                        </div>
                    </div>
                </div>

            </section>

        </div>
        {% endblock %}
    </div>
</div>

src/mysite/resources/templates/resources/evaluacion.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Evaluacion</title>
</head>
<body>

</body>
</html>

src/mysite/resources/templates/resources/form-template-lectura.html
{% load staticfiles %}
<!--<link rel="stylesheet" type="text/css" href="{% static 'resources/style.css' %}"/>-->


<div style="padding-left: 2cm" class="form-group">
    <div class="col-sm-15">
        <label for="id_titulo" class="col-sm-offset-3 col-sm-10">Titulo</label>
        <input type="text" id="id_titulo" name="titulo">

    </div>

    <br>
    <label for="id_texto" class="col-sm-offset-3 col-sm-10">Texto: </label>
    <div class="col-sm-15">
        <textarea cols="40" rows="10" style="border: solid; border-color: black " id="id_texto" name="texto"></textarea>
    </div>

</div>



<div class="form-group">
    <div class="col-sm-offset-3 col-sm-20">
        <span class="text-danger small">{{ field.errors }}</span>
    </div>
    <label class="control-label col-sm-5">{{ field.label_tag }}</label>
</div>

<div style="padding-left: 2cm" class="form-group">
    <div class="col-sm-offset-5 col-sm-15">
        <input type="file" id="file" class="btn btn-success" title="Cargar"/>
    </div>
</div>

<br>

<script>
    function readTextFile(file, callback, encoding) {
        var reader = new FileReader();
        reader.addEventListener('load', function (e) {
            callback(this.result);
        });
        if (encoding) reader.readAsText(file, encoding);
        else reader.readAsText(file);
    }

    function fileChosen(input, output) {
        if (input.files && input.files[0]) {
            readTextFile(
                input.files[0],
                function (str) {
                    output.value = str;
                }
            );
        }
    }

    $('#file').on('change', function () {
        fileChosen(this, document.getElementById('id_texto'));
    });
</script>